version: 2
jobs:
  android:
    working_directory: ~/repo
    branches:
      only:
        - develop
    docker:
      - image: reactnativecommunity/react-native-android
    steps:
      - checkout
      - run: npx envinfo
      - run: npm install
      - run: cd android && ./gradlew assembleRelease
      - store_artifacts:
          path: android/app/build/outputs/apk/release
workflows:
  version: 2
  build_and_test:
    jobs:
      - android